# Generated by Django 3.0.4 on 2020-05-01 15:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('category', models.CharField(choices=[(1, 'Travel'), (2, 'Weekend'), (3, 'Private'), (4, 'Test'), (5, 'Test2')], default='no', max_length=10)),
                ('tags', models.CharField(blank=True, max_length=200, verbose_name='Tags')),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Published Date')),
                ('text', models.TextField(blank=True, verbose_name='Text')),
            ],
        ),
    ]
