# Generated by Django 3.0.4 on 2020-05-01 16:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200501_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_Entries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('tags', models.CharField(blank=True, max_length=200, verbose_name='Tags')),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Published Date')),
                ('text', models.TextField(blank=True, verbose_name='Text')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200, verbose_name='Category')),
                ('description', models.CharField(max_length=600, verbose_name='Description')),
            ],
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.AddField(
            model_name='blog_entries',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.Category'),
        ),
    ]
