# Generated by Django 3.0.4 on 2020-05-01 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200501_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_entries',
            name='summary',
            field=models.TextField(blank=True, verbose_name='Text'),
        ),
    ]
