# Generated by Django 3.1.2 on 2020-10-26 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_entries_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_entries',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='blog_entries',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='blog_entries',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='blog_entries',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='blog_entries',
            name='text2',
            field=models.TextField(blank=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='blog_entries',
            name='text3',
            field=models.TextField(blank=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='blog_entries',
            name='text4',
            field=models.TextField(blank=True, verbose_name='Text'),
        ),
    ]
