# Generated by Django 3.1.2 on 2020-10-26 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20201026_2317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog_entries',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='blog_entries',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='blog_entries',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='blog_entries',
            name='image5',
        ),
        migrations.RemoveField(
            model_name='blog_entries',
            name='text2',
        ),
        migrations.RemoveField(
            model_name='blog_entries',
            name='text3',
        ),
        migrations.RemoveField(
            model_name='blog_entries',
            name='text4',
        ),
    ]
