# Generated by Django 3.1.2 on 2020-11-09 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20201026_2325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog_entries',
            old_name='text',
            new_name='text1',
        ),
        migrations.AddField(
            model_name='blog_entries',
            name='picture1',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='blog_entries',
            name='picture2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='blog_entries',
            name='picture3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='blog_entries',
            name='picture4',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='blog_entries',
            name='text2',
            field=models.TextField(blank=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='blog_entries',
            name='text3',
            field=models.TextField(blank=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='blog_entries',
            name='text4',
            field=models.TextField(blank=True, verbose_name='Text'),
        ),
    ]
